defaults: &defaults
  environment:
    - SOURCE_DIR: /tmp/site/_site
    - S3_BUCKET: macaduck19
    - S3_REGION: us-east-1
version: 2
jobs:
  deploy:
    <<: *defaults
    docker:
       - image: circleci/python:2.7-jessie
    steps:
      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - run: sudo apt-get install git-lfs
      - run: git lfs install
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Upload to s3
          command: aws s3 sync $SOURCE_DIR s3://$S3_BUCKET --delete
  install:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: sudo installer -pkg munkitools-3.5.2.3637.pkg -target /
      - run: sudo defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL "http://macaduck19.s3-website-us-east-1.amazonaws.com"
      - run: sudo /usr/local/munki/managedsoftwareupdate
      - run: sudo /usr/local/munki/managedsoftwareupdate --installonly

workflows:
  version: 2
  commit:
    jobs:
      - upload
      - install