defaults: &defaults
  environment:
    - S3_BUCKET: macaduck19
    - S3_REGION: us-east-1
version: 2
jobs:
  upload:
    <<: *defaults
    docker:
       - image: circleci/python:2.7-jessie
    steps:
      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - run: sudo apt-get install git-lfs
      - run: git lfs install
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Upload to s3
          command: aws s3 sync . s3://$S3_BUCKET --exclude ".git/*" --delete --acl public-read
  install:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - run: curl -OL https://github.com/munki/munki/releases/download/v3.5.2/munkitools-3.5.2.3637.pkg
      - run: sudo installer -pkg munkitools-3.5.2.3637.pkg -target /
      - run: sudo defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL "https://s3.amazonaws.com/macaduck19"
      - run: sudo /usr/local/munki/managedsoftwareupdate -vvv
      - run: sudo /usr/local/munki/managedsoftwareupdate --installonly -vvv

workflows:
  version: 2
  commit:
    jobs:
      - upload:
          filters:
            branches:
              only: master
      - install:
          filters:
            branches:
              only: master
          requires:
           - upload